apiVersion: v1
kind: Service
metadata:
  name: ogre-svc
  labels:
    app.kubernetes.io/name: ogre-svc
spec:
  selector:
    app.kubernetes.io/name: ogre-svc
  ports:
    - name: http
      port: 8080
      targetPort: http
